version: '3'
services:
  coral-backend:
    build:
      context: .
    container_name: 'coral-backend'
    env_file: .env
    environment:
      - MONGO_HOSTNAME=coral-db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '3000:3000'
    links:
      - 'mongo'
    depends_on:
      - 'mongo'
    networks:
      - coral
  mongo:
    image: 'mongo:latest'
    container_name: coral-db
    environment: 
      - MONGO_INITDB_DATABASE=coral-db
    ports:
      - '27017:27017'
    networks:
      - coral
networks:
  coral:
